### ISSUE TITLE
MacBook M1芯片编译不通过

### ISSUE THREAD

**Issue by codeyifei** [Hyperledger-TWGC/ccs-gm#30]
当使用M1芯片的mac进行项目开发的时候，报错编译失败
![image](https://user-images.githubusercontent.com/30040950/128107306-41238d96-f6d8-4eb4-9d88-159fad8c2d08.png)
![image](https://user-images.githubusercontent.com/30040950/128107325-2106e85b-6d41-4918-9916-d38c0fd9beca.png)
猜测原因应该是包只有amd64架构的代码，而没有arm64架构的对应代码，所以找不到对应的函数，求教该问题应该如何解决

**Comment by codeyifei** [comment]
具体报错信息：
![image](https://user-images.githubusercontent.com/30040950/128107472-f9fba0e9-eae4-4564-8715-d197c9534427.png)
PS：由于项目较老，包引用采用copy的方式，而非go mod

**Comment by JulienGuo** [comment]
能否把代码合并在一个分支下，根据runtime.GOARCH判断架构，这样代码维护就相对简洁一些。

**Comment by triplewz** [comment]
已经修复bug，但是没有使用arm汇编优化，所以性能会差一点，已提交pr #32

**Comment by davidkhala** [comment]
我们公司云上面的free-tier每个月大概有1core 1G 内存的ARM compute，可以拿来设置一下github self-host runner

**Comment by davidkhala** [comment]
Fixed by #32
