### ISSUE TITLE
项目重命名

### ISSUE THREAD

**Issue by davidkhala** [Hyperledger-TWGC/ccs-gm#4]
@yzwyzwyzw1 @suchongming 
云龙，志伟，此issue用于讨论项目重命名问题

**Comment by yzwyzwyzw1** [comment]
我提议修改为cetc-gm,cetc是中国网安的英文名，见名知意

**Comment by yzwyzwyzw1** [comment]
cetccs-gm，提议这个项目库名字

**Comment by davidkhala** [comment]
ccs-gm我觉得也够了，因为已经是China Crypto Security的缩写

**Comment by suchongming** [comment]
三个项目应该是统一的格式，我统一两位的建议，公司或组织名-gm 或 公司或组织名-ccs
