### ISSUE TITLE
支持将SM2.PrivateKey 导出成为PEM格式

### ISSUE THREAD

**Issue by davidkhala** [Hyperledger-TWGC/ccs-gm#7]
Now x509.MarshalECPrivateKey could accept an sm2.PrivateKey as input and serialize sm2 private key into DER format.  
But I could not find a way to export it this key as PEM. It is required in interopt test. 
@suchongming 云龙你能帮忙看下么？看起来现在已经支持序列化成为DER格式了
你也可以将这个issue assign给我，如果这样的话，我会从别的基础库中借鉴几段格式转换代码

**Comment by suchongming** [comment]
好的，我添加两个接口，分别用于导入导出。

**Comment by suchongming** [comment]
已添加
